package top.liuwei.xbvr;
import top.liuwei.xbvr.domain.Models;
import org.junit.Test;
import org.json.*;
import static org.junit.Assert.*;
import java.util.*;

public class CoreTest {
    @Test public void exactLegacyModeKeys(){String[] keys={"180_LR","FISHEYE_180_LR","FISHEYE_190_LR","FISHEYE_200_LR","FISHEYE_220_LR","360_LR","360_TB","180_MONO","360","FISHEYE_200","FISHEYE_220","SBS_MONO","NONE"};int[] kinds={1,2,2,2,2,1,1,1,1,2,2,0,0},angles={180,180,190,200,220,360,360,180,360,200,220,180,180},layouts={1,1,1,1,1,1,2,0,0,0,0,1,0};for(int i=0;i<keys.length;i++){Projection p=Projection.infer(keys[i],"","",0);assertTrue(keys[i],p.known);assertEquals(keys[i],kinds[i],p.kind);assertEquals(keys[i],angles[i],p.capture);assertEquals(keys[i],layouts[i],p.layout);}}
    @Test public void metadataPriorityAndTokenBoundaries(){assertEquals(Projection.EQUIRECT,Projection.infer("180_sbs","sample_RF52_180_SBS.mp4","",0).kind);assertEquals(Projection.TB,Projection.infer("360_tb","sample_mono.mp4","",0).layout);assertEquals(Projection.SBS,Projection.infer("none","sample_SBS.mp4","",0).layout);assertFalse(Projection.infer("","Atmosphere_5180_cubehouse_MKX999.mp4","",0).known);assertFalse(Projection.infer("equirectangular360","sample_front_back_fisheye.mp4","",0).known);assertEquals(Projection.MONO,Projection.infer("fisheye190","sample_TB.mp4","mono",190).layout);}
    @Test public void authValidatesBothMarkers()throws Exception{Protocol.authorized(new JSONObject().put("authorized",true));try{Protocol.authorized(new JSONObject().put("authorized",1).put("access",0));fail();}catch(IllegalStateException expected){}assertTrue(Protocol.sameOrigin("HTTPS://HOST.test/proxy","https://host.test:443/scene"));assertFalse(Protocol.sameOrigin("https://host.test","https://user:pass@host.test/a"));}
    @Test public void stableObjectKeysPreserveTypesAndProxyPrefixes(){assertEquals(Protocol.identity("https://host/proxy/deovr/12?dnt=true"),Protocol.identity("https://host/proxy/heresphere/12?session=abc"));assertEquals(Protocol.identity("https://host/proxy/deovr/file/12?dnt=true"),Protocol.identity("https://host/proxy/api/dms/file/12/title?session=abc"));assertNotEquals(Protocol.identity("https://host/proxy/deovr/12"),Protocol.identity("https://host/proxy/deovr/file/12"));assertNotEquals(Protocol.identity("https://host/a/deovr/12"),Protocol.identity("https://host/b/deovr/12"));assertEquals("",Protocol.fileId("https://host/video.mp4?redirect=/api/dms/file/12"));assertEquals("12",Protocol.fileId("https://host/api/dms/file/12/title?dnt=true"));}
    @Test public void fileMetadataDoesNotCopyOtherSceneFile()throws Exception{Models.Source a=new Models.Source(),b=new Models.Source();a.stereo="tb";a.fov=220;Protocol.fileMetadata(a,new JSONObject("{\"filename\":\"a.mp4\",\"projection\":\"360_tb\",\"video_width\":4096,\"video_height\":4096}"));Protocol.fileMetadata(b,new JSONObject("{\"filename\":\"b_RF52.mp4\",\"projection\":\"rf52\",\"video_width\":8192,\"video_height\":4096}"));assertEquals("tb",a.stereo);assertEquals(220,a.fov,0);assertEquals(4096,a.width);assertEquals(8192,b.width);assertEquals("",b.stereo);assertEquals(0,b.fov,0);assertEquals(190,Projection.infer(b.projection,b.filename,b.stereo,b.fov).capture);}
    @Test public void all21ProjectionLayoutCombinationsInfer(){for(String projection:new String[]{"flat","180","sphere","fisheye180","fisheye190","fisheye200","fisheye220"})for(int layout=0;layout<3;layout++){Projection p=Projection.infer(projection,"",new String[]{"mono","sbs","tb"}[layout],0);assertTrue(projection,p.known);assertEquals(projection,layout,p.layout);}}
    @Test public void explicitFileModeBeatsSceneStereoAndGenericFishCanRefine(){assertEquals(Projection.TB,Projection.infer("360_tb","x_mono.mp4","sbs",0).layout);assertEquals(190,Projection.infer("fisheye","sample_RF52_SBS.mp4","sbs",0).capture);assertEquals(200,Projection.infer("fisheye","sample_MKX200_SBS.mp4","sbs",0).capture);assertEquals(190,Projection.infer("fisheye190","sample_MKX220_SBS.mp4","sbs",0).capture);}
    @Test public void invalidDirectionCannotProduceNan(){Projection p=new Projection();assertNull(p.map(0,0,0,1920,1080));assertNull(p.map(Double.NaN,0,1,1920,1080));assertNull(p.map(0,0,1,0,1080));}
    @Test public void flatPackingHintsDistinguishFullEyeAspect(){assertFalse(Projection.infer("flat","sample_FULL_SBS.mp4","",0).halfPacked);assertFalse(Projection.infer("flat","sample_FSBS.mp4","",0).halfPacked);assertFalse(Projection.infer("flat","sample_FTB.mp4","",0).halfPacked);Projection half=Projection.infer("flat","sample_HSBS.mp4","",0);assertEquals(Projection.SBS,half.layout);assertTrue(half.halfPacked);}
    @Test public void urlsPreservePrefixAndQuery(){assertEquals("https://host.test/proxy",Protocol.base("https://host.test/proxy/deovr/"));assertEquals("https://host.test/proxy",Protocol.base("https://host.test/proxy/heresphere/"));assertEquals("https://host.test/proxy/media.mp4?token=a%2Fb",Protocol.resolve("https://host.test/proxy","media.mp4?token=a%2Fb"));assertEquals("https://other.test/a?x=y",Protocol.resolve("https://host.test/proxy","https://other.test/a?x=y"));assertTrue(Protocol.sameOrigin("https://a.test","https://a.test:443/video"));assertFalse(Protocol.sameOrigin("https://a.test","http://a.test/video"));}
    @Test public void http200AuthFailureIsRejected()throws Exception{for(String key:List.of("authorized","access"))for(int status:new int[]{-1,0}){try{Protocol.authorized(new JSONObject().put(key,status));fail();}catch(IllegalStateException expected){}}Protocol.authorized(new JSONObject().put("authorized","1"));}
    @Test public void duplicateGroupsKeepMembership()throws Exception{String fixture="{\"authorized\":\"1\",\"scenes\":[{\"name\":\"Recent\",\"list\":[{\"title\":\"Test\",\"video_url\":\"deovr/1\",\"videoLength\":12}]},{\"name\":\"Favorite\",\"list\":[{\"title\":\"Test\",\"video_url\":\"deovr/1\"}]}]}";var l=Protocol.library(new JSONObject(fixture),"http://server/proxy");assertEquals(1,l.size());assertEquals(2,l.get(0).groups.size());assertEquals(12000,l.get(0).duration);}
    @Test public void timeUnitsAndFlexibleResolution()throws Exception{var d=Protocol.detail(new JSONObject("{\"authorized\":1,\"videoLength\":12.5,\"timeStamps\":[{\"ts\":2.25,\"name\":\"A\"}],\"encodings\":[{\"videoSources\":[{\"resolution\":1080,\"url\":\"video.mp4?dnt=true\"}]}]}"),"http://s",false);assertEquals(12500,d.duration);assertEquals(2250,d.tags.get(0).time);assertTrue(d.sources.get(0).url.endsWith("?dnt=true"));var h=Protocol.detail(new JSONObject("{\"access\":1,\"duration\":12500,\"tags\":[{\"name\":\"Category\"},{\"start\":2250,\"name\":\"A\"}],\"media\":[{\"sources\":[{\"resolution\":\"1080\",\"url\":\"a.mp4\"}]}]}"),"http://s",true);assertEquals(d.duration,h.duration);assertEquals(1,h.tags.size());assertEquals(2250,h.tags.get(0).time);assertEquals(1,h.sources.size());assertFalse(h.writeFavorite);}
    @Test public void referenceModesAndLensNames(){String[][] f={{"180_sbs","", "1","180","1"},{"fisheye","","2","180","1"},{"rf52","","2","190","1"},{"mkx200","","2","200","1"},{"vrca220","","2","220","1"},{"360_lr","","1","360","1"},{"360_tb","","1","360","2"},{"180_mono","","1","180","0"},{"360_mono","","1","360","0"},{"fisheye200_mono","","2","200","0"},{"fisheye220_mono","","2","220","0"},{"flat","sample_3dh.mp4","0","180","1"},{"flat","","0","180","0"}};for(String[] row:f){Projection p=Projection.infer(row[0],row[1],"",0);assertEquals(Arrays.toString(row),Integer.parseInt(row[2]),p.kind);assertEquals(Integer.parseInt(row[3]),p.capture);assertEquals(Integer.parseInt(row[4]),p.layout);}assertEquals(220,Projection.infer("","SAMPLE_MKX22_180_3dh.mp4","",0).capture);assertEquals(190,Projection.infer("dome","RF52_180_SBS.mp4","sbs",0).capture);assertEquals(Projection.FLAT,Projection.infer("flat","RF52_180.mp4","mono",0).kind);assertFalse(Projection.infer("","unknown.mp4","",0).known);assertFalse(Projection.infer("","front_back_dual_fisheye_360.mp4","",0).known);}
    @Test public void completeMatrixHasCorrectEyeAndCenter(){for(int kind:new int[]{Projection.EQUIRECT,Projection.FISHEYE})for(int angle:kind==1?new int[]{180,360}:new int[]{180,190,200,220})for(int layout=0;layout<3;layout++)for(int eye=0;eye<2;eye++){Projection p=new Projection();p.kind=kind;p.capture=angle;p.layout=layout;p.eye=eye;double[] uv=p.map(0,0,1,4000,2000);assertEquals(layout==1?(eye+.5)*.5:.5,uv[0],1e-6);assertEquals(layout==2?(eye+.5)*.5:.5,uv[1],1e-6);}}
    @Test public void fisheyeRadiusUsesActualEyePixels(){Projection p=new Projection();p.kind=Projection.FISHEYE;p.capture=200;p.layout=Projection.MONO;double a=Math.toRadians(50);double[] uv=p.map(Math.sin(a),0,Math.cos(a),4000,2000);assertEquals(.625,uv[0],1e-6);assertEquals(.5,uv[1],1e-6);uv=p.map(0,Math.sin(a),Math.cos(a),4000,2000);assertEquals(.25,uv[1],1e-6);p.layout=Projection.SBS;uv=p.map(Math.sin(a),0,Math.cos(a),4000,2000);assertEquals(.375,uv[0],1e-6);}
    @Test public void fishBoundariesAndOrientation(){for(int angle:new int[]{180,190,200,220}){Projection p=new Projection();p.kind=2;p.capture=angle;double boundary=Math.toRadians(angle/2.0-.001);assertNotNull(p.map(Math.sin(boundary),0,Math.cos(boundary),2000,2000));double outside=Math.toRadians(angle/2.0+.001);assertNull(p.map(Math.sin(outside),0,Math.cos(outside),2000,2000));double[] up=p.map(0,.5,Math.sqrt(.75),2000,2000);assertTrue(up[1]<.5);p.mirror=true;double[] right=p.map(.5,0,Math.sqrt(.75),2000,2000);assertTrue(right[0]<.5);}}
    @Test public void panoramaKnownDirections(){Projection p=new Projection();p.kind=1;p.capture=360;assertEquals(.75,p.map(1,0,0,4000,2000)[0],1e-6);assertEquals(0,p.map(0,1,0,4000,2000)[1],1e-6);p.capture=180;assertEquals(1,p.map(1,0,0,2000,2000)[0],1e-6);assertNull(p.map(1,0,-.01,2000,2000));}
}
